// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        (unknown)
// source: namespace/namespace.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Namespace struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Identifier string   `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Owner      string   `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Tags       []string `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
}

func (x *Namespace) Reset() {
	*x = Namespace{}
	if protoimpl.UnsafeEnabled {
		mi := &file_namespace_namespace_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Namespace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Namespace) ProtoMessage() {}

func (x *Namespace) ProtoReflect() protoreflect.Message {
	mi := &file_namespace_namespace_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Namespace.ProtoReflect.Descriptor instead.
func (*Namespace) Descriptor() ([]byte, []int) {
	return file_namespace_namespace_proto_rawDescGZIP(), []int{0}
}

func (x *Namespace) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *Namespace) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *Namespace) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

var File_namespace_namespace_proto protoreflect.FileDescriptor

var file_namespace_namespace_proto_rawDesc = []byte{
	0x0a, 0x19, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x2f, 0x6e, 0x61, 0x6d, 0x65,
	0x73, 0x70, 0x61, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x55, 0x0a, 0x09, 0x4e,
	0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x69, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x77, 0x6e, 0x65,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x74, 0x61,
	0x67, 0x73, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x65, 0x64, 0x6f, 0x62, 0x74, 0x63, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x6b, 0x69, 0x74,
	0x2f, 0x72, 0x70, 0x63, 0x2f, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x2f, 0x76,
	0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_namespace_namespace_proto_rawDescOnce sync.Once
	file_namespace_namespace_proto_rawDescData = file_namespace_namespace_proto_rawDesc
)

func file_namespace_namespace_proto_rawDescGZIP() []byte {
	file_namespace_namespace_proto_rawDescOnce.Do(func() {
		file_namespace_namespace_proto_rawDescData = protoimpl.X.CompressGZIP(file_namespace_namespace_proto_rawDescData)
	})
	return file_namespace_namespace_proto_rawDescData
}

var file_namespace_namespace_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_namespace_namespace_proto_goTypes = []interface{}{
	(*Namespace)(nil), // 0: Namespace
}
var file_namespace_namespace_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_namespace_namespace_proto_init() }
func file_namespace_namespace_proto_init() {
	if File_namespace_namespace_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_namespace_namespace_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Namespace); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_namespace_namespace_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_namespace_namespace_proto_goTypes,
		DependencyIndexes: file_namespace_namespace_proto_depIdxs,
		MessageInfos:      file_namespace_namespace_proto_msgTypes,
	}.Build()
	File_namespace_namespace_proto = out.File
	file_namespace_namespace_proto_rawDesc = nil
	file_namespace_namespace_proto_goTypes = nil
	file_namespace_namespace_proto_depIdxs = nil
}
